export const regions = [
  "Richmond, Virginia, USA",
  "San Antonio, Texas, USA",
  "Moses Lake, Washington, USA",
  "Phoenix, Arizona, USA",
  "Sydney, Australia",
  "Singapore, Singapore",
  "Dublin, Ireland",
  "Stockholm, Sweden",
  "London, England",
  "Amsterdam, Netherlands",
  "Des Moines, Iowa, USA",
  "Johannesburg, South Africa",
  "Pune, India",
  "Hong Kong",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Toronto, Canada",
  "Paris, France",
  "Frankfurt, Germany",
  "Oslo, Norway",
  "Warsaw, Poland",
  "Zurich, Switzerland",
  "Dubai, UAE",
  "São Paulo, Brazil",
  "Doha, Qatar",
  "Busan, Korea South",
  "Northlake, Illinois, USA",
  "San Francisco, California, USA",
  "Mumbai, India",
  "Cheyenne, Wyoming, USA",
  "Cape Town, South Africa",
  "Canberra, Australia",
  "Australia Central 2",
  "Melbourne, Australia",
  "Osaka, Japan",
  "Jio India Central",
  "Busan, South Korea",
  "Chennai, India",
  "Ahmedabad, India",
  "Montreal, Canada",
  "Marseille, France",
  "Bergen, Norway",
  "Geneva, Switzerland",
  "Cardiff, UK",
  "Abu Dhabi, UAE",
  "Rio de Janeiro, Brazil"
]
